---
# tasks file for tomcatroles
- name: updating ubuntu
  apt:
    update_cache: yes
    state: present
- name: installing java
  package:
    name: openjdk-8-jdk
    state: present
- name: creating tomcat group
  group:
    name: tomcat
    state: present
- name: creating tomcat user
  user: 
    name: tomcat
    shell: /bin/false
    comment: tomcat done
    group: tomcat
- name: Go to the folder
  shell: cd /tmp/
- name: downloading tomcat
  get_url:
    url: "{{ tomcat_version_url }}"
    dest: /tmp/
- name: creating /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755
- name: unarchive tomcat
  unarchive:
    src: "/tmp/{{ tomcat_tar_file }}"
    dest: /opt/tomcat
    extra_opts: 
    - --strip-components=1
    remote_src: yes
- name: change th directory to /opt/tomcat
  shell: cd /opt/tomcat
- name: Change ownership of Tomcat installation
  file: 
    path: /opt/tomcat
    owner: tomcat 
    group: tomcat 
    state: directory 
    recurse: yes 
- name: creating  systemd service file
  template:
    src: ./tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
- name: stating tomcat
  systemd:
    state: started
    daemon_reload: yes
    name: tomcat
- name: Configure Tomcat users
  template: 
    src: templates/tomcat-users.xml.j2 
    dest: /opt/tomcat/conf/tomcat-users.xml
    mode: 0755
  notify:
    restart tomcat 
- name: configure Manager
  template: 
    src: templates/context.xml.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
- name: configure Host-Manager
  template: 
    src: templates/context.xml.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
  notify:
    restart tomcat
- name: copying  gameoflife war file to web apps
  copy:
    src: "{{ war_file_location }}"
    dest: /opt/tomcat/webapps/
  notify:
    restart tomcat